### ISSUE TITLE
Orchestrion Plugin失效

### ISSUE THREAD

**Issue by zxwqwq** [ottercorp/DalamudPluginsD17#129]
不知是否有关，日志报错如下：
18:07:23.069 ERR | Exception during raise of "Void <InvokeSafely>b__0()"
18:07:23.069 ERR | System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
18:07:23.069 ERR |    at Orchestrion.Util.ClientLangCode() in /work/repo/Orchestrion/Util.cs:line 79
18:07:23.069 ERR |    at Orchestrion.OrchestrionPlugin.GetClientSongName(Int32 songId) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 413
18:07:23.069 ERR |    at Orchestrion.OrchestrionPlugin.UpdateDtr(Int32 songId, Boolean playedByOrch) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 379
18:07:23.069 ERR |    at Orchestrion.OrchestrionPlugin.OnSongChanged(Int32 oldSong, Int32 newSong, Int32 oldSecondSong, Int32 oldCurrentSong, Boolean oldPlayedByOrch, Boolean playedByOrch) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 144
18:07:23.069 ERR |    at Orchestrion.Audio.BGMManager.InvokeSongChanged(Int32 oldSongId, Int32 newSongId, Int32 oldSecondSongId, Int32 newSecondSongId, Boolean oldPlayedByOrch, Boolean playedByOrch) in /work/repo/Orchestrion/Audio/BGMManager.cs:line 166
18:07:23.069 ERR |    at Orchestrion.Audio.BGMManager.HandleSongChanged(Int32 oldSong, Int32 newSong, Int32 oldSecondSong, Int32 newSecondSong) in /work/repo/Orchestrion/Audio/BGMManager.cs:line 87
18:07:23.069 ERR |    at Orchestrion.BGMSystem.BGMController.Update() in /work/repo/Orchestrion/BGMSystem/BGMController.cs:line 155
18:07:23.069 ERR |    at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)

**Comment by zxwqwq** [comment]
今日更新后仍然无法正常工作，报错日志如下：
17:40:30.340 ERR | Exception during raise of "Void <InvokeSafely>b__0()"
17:40:30.340 ERR | System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
17:40:30.340 ERR |    at Orchestrion.Util.ClientLangCode() in /work/repo/Orchestrion/Util.cs:line 84
17:40:30.340 ERR |    at Orchestrion.OrchestrionPlugin.GetClientSongName(Int32 songId) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 416
17:40:30.340 ERR |    at Orchestrion.OrchestrionPlugin.UpdateDtr(Int32 songId, Boolean playedByOrch) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 382
17:40:30.340 ERR |    at Orchestrion.OrchestrionPlugin.OnSongChanged(Int32 oldSong, Int32 newSong, Int32 oldSecondSong, Int32 oldCurrentSong, Boolean oldPlayedByOrch, Boolean playedByOrch) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 147
17:40:30.340 ERR |    at Orchestrion.Audio.BGMManager.InvokeSongChanged(Int32 oldSongId, Int32 newSongId, Int32 oldSecondSongId, Int32 newSecondSongId, Boolean oldPlayedByOrch, Boolean playedByOrch) in /work/repo/Orchestrion/Audio/BGMManager.cs:line 166
17:40:30.340 ERR |    at Orchestrion.Audio.BGMManager.HandleSongChanged(Int32 oldSong, Int32 newSong, Int32 oldSecondSong, Int32 newSecondSong) in /work/repo/Orchestrion/Audio/BGMManager.cs:line 87
17:40:30.340 ERR |    at Orchestrion.BGMSystem.BGMController.Update() in /work/repo/Orchestrion/BGMSystem/BGMController.cs:line 155
17:40:30.340 ERR |    at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)

**Comment by zxwqwq** [comment]
报错日志2：
17:42:41.678 ERR | Exception during raise of "Void Draw()"
17:42:41.678 ERR | System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
17:42:41.678 ERR |    at Orchestrion.Util.ClientLangCode() in /work/repo/Orchestrion/Util.cs:line 84
17:42:41.678 ERR |    at Orchestrion.OrchestrionPlugin.GetClientSongName(Int32 songId) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 416
17:42:41.678 ERR |    at Orchestrion.OrchestrionPlugin.UpdateDtr(Int32 songId, Boolean playedByOrch) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 382
17:42:41.678 ERR |    at Orchestrion.OrchestrionPlugin.OnSongChanged(Int32 oldSong, Int32 newSong, Int32 oldSecondSong, Int32 oldCurrentSong, Boolean oldPlayedByOrch, Boolean playedByOrch) in /work/repo/Orchestrion/OrchestrionPlugin.cs:line 147
17:42:41.678 ERR |    at Orchestrion.Audio.BGMManager.InvokeSongChanged(Int32 oldSongId, Int32 newSongId, Int32 oldSecondSongId, Int32 newSecondSongId, Boolean oldPlayedByOrch, Boolean playedByOrch) in /work/repo/Orchestrion/Audio/BGMManager.cs:line 166
17:42:41.678 ERR |    at Orchestrion.Audio.BGMManager.Play(Int32 songId, Boolean isReplacement) in /work/repo/Orchestrion/Audio/BGMManager.cs:line 125
17:42:41.678 ERR |    at Orchestrion.UI.Components.RenderableSongList.DrawSongListItem(RenderableSongEntry entry, Int32 index) in /work/repo/Orchestrion/UI/Components/RenderableSongList.cs:line 141
17:42:41.678 ERR |    at Orchestrion.UI.Components.RenderableSongList.<Draw>b__11_0(RenderableSongEntry entry, Int32 index) in /work/repo/Orchestrion/UI/Components/RenderableSongList.cs:line 79
17:42:41.678 ERR |    at Orchestrion.UI.Components.RenderableSongList.Draw() in /work/repo/Orchestrion/UI/Components/RenderableSongList.cs:line 89
17:42:41.678 ERR |    at Orchestrion.UI.Windows.MainWindow.MainWindow.DrawSongListTab() in /work/repo/Orchestrion/UI/Windows/MainWindow/MainWindow.SongList.cs:line 12
17:42:41.678 ERR |    at Orchestrion.UI.Windows.MainWindow.MainWindow.Draw() in /work/repo/Orchestrion/UI/Windows/MainWindow/MainWindow.Root.cs:line 161
17:42:41.678 ERR |    at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration)
17:42:41.678 ERR |    at Dalamud.Interface.Windowing.WindowSystem.Draw()
17:42:41.678 ERR |    at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)
